name: Run Priyansh-Bot-V2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # كل ساعتين

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # يوقف بعد 6 ساعات كحد أقصى (حد GitHub)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the bot
        run: node index.js  # أو npm start حسب ما عندك